discord:
  token: "Bot Token"
  guildId: "Discord Server ID"

linkCode:
  expiryInMinutes: 5 #Default Value
  codeLength: 6 #Default Value

roles:
  default: "0000000000000000000"
  Role1: "0000000000000000000"
  Role2: "0000000000000000000"
  Role3: "0000000000000000000"
  Role4: "0000000000000000000"
  Role5: "0000000000000000000"
  Role6: "0000000000000000000"
  Role7: "0000000000000000000"
  Role8: "0000000000000000000"
  Role9: "0000000000000000000"

linkMessage:
  prefix: "✉ Click "
  linkText: " [HERE] "
  linkUrl: "Your Discord Bot OAuth URL here"
  hoverText: "Click the link to link your MC Account to Discord."
  suffix: " to link your Discord account."

linkedMessage:
  linked: "✅ Your account is already linked to Discord."

webhook:
  linkSync: "Your Webhook URL"

mysql:
  host: "localhost"
  port: 3306
  database: "ogmcdc"
  username: "username"
  password: "password"
