discord:
  token: "BotToken"
  guildId: "DiscordServerID"
  clientId: "DiscordAppClientID"
  clientSecret: "DiscordAppSecret"
  redirectUrl: "DiscordAppRedirectURL"

linkCode:
  expiryInMinutes: 5
  codeLength: 6

roles:
  owner: "0000000000000000000"
  default: "0000000000000000000"

linkMessage:
  prefix: "✉ Click "
  linkText: " [HERE] "
  linkUrl: "https://discord.com/oauth2/authorize"
  hoverText: "Linking your account gives you the first Rank for free."
  suffix: " to link your Discord account."

reward:
  linkreward: "false"
  linkrank: "default"

linkedMessage:
  linked: "✅ Your account is already linked to Discord."

webhook:
  linkSync: "DiscordAppURI"

mysql:
  host: "localhost"
  port: 3306
  database: "database"
  username: "username"
  password: "Password"
